/**
 * Control Your Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BudgetRequest model module.
* @module model/BudgetRequest
* @version Unknown
*/
export default class BudgetRequest {
    /**
    * Constructs a new <code>BudgetRequest</code>.
    * @alias module:model/BudgetRequest
    * @class
    * @param name {String} 
    */

    constructor(name) {
        
        
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>BudgetRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BudgetRequest} obj Optional instance to populate.
    * @return {module:model/BudgetRequest} The populated <code>BudgetRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BudgetRequest();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;




}
