/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CategoryGroup from './CategoryGroup';
import Month from './Month';

/**
* The Budget model module.
* @module model/Budget
* @version Unknown
*/
export default class Budget {
    /**
    * Constructs a new <code>Budget</code>.
    * @alias module:model/Budget
    * @class
    * @param url {String} 
    * @param id {String} 
    * @param name {String} 
    * @param lastModified {Date} 
    * @param months {Array.<module:model/Month>} 
    * @param categoryGroups {Array.<module:model/CategoryGroup>} 
    */

    constructor(url, id, name, lastModified, months, categoryGroups) {
        
        
        this['url'] = url;
        this['id'] = id;
        this['name'] = name;
        this['last_modified'] = lastModified;
        this['months'] = months;
        this['categoryGroups'] = categoryGroups;
        
    }

    /**
    * Constructs a <code>Budget</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Budget} obj Optional instance to populate.
    * @return {module:model/Budget} The populated <code>Budget</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Budget();
                        
            
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('last_modified')) {
                obj['last_modified'] = ApiClient.convertToType(data['last_modified'], 'Date');
            }
            if (data.hasOwnProperty('months')) {
                obj['months'] = ApiClient.convertToType(data['months'], [Month]);
            }
            if (data.hasOwnProperty('categoryGroups')) {
                obj['categoryGroups'] = ApiClient.convertToType(data['categoryGroups'], [CategoryGroup]);
            }
        }
        return obj;
    }

    /**
    * @member {String} url
    */
    'url' = undefined;
    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Date} last_modified
    */
    'last_modified' = undefined;
    /**
    * @member {Array.<module:model/Month>} months
    */
    'months' = undefined;
    /**
    * @member {Array.<module:model/CategoryGroup>} categoryGroups
    */
    'categoryGroups' = undefined;




}
