/**
 * Control Your Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';

/**
* The CategoryGroup model module.
* @module model/CategoryGroup
* @version Unknown
*/
export default class CategoryGroup {
    /**
    * Constructs a new <code>CategoryGroup</code>.
    * @alias module:model/CategoryGroup
    * @class
    * @param url {String} 
    * @param id {String} 
    * @param name {String} 
    * @param categories {Array.<module:model/Category>} 
    */

    constructor(url, id, name, categories) {
        
        
        this['url'] = url;
        this['id'] = id;
        this['name'] = name;
        this['categories'] = categories;
        
    }

    /**
    * Constructs a <code>CategoryGroup</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CategoryGroup} obj Optional instance to populate.
    * @return {module:model/CategoryGroup} The populated <code>CategoryGroup</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryGroup();
                        
            
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('hidden')) {
                obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], [Category]);
            }
        }
        return obj;
    }

    /**
    * @member {String} url
    */
    'url' = undefined;
    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Boolean} hidden
    */
    'hidden' = undefined;
    /**
    * @member {Boolean} deleted
    */
    'deleted' = undefined;
    /**
    * @member {Array.<module:model/Category>} categories
    */
    'categories' = undefined;




}
