/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Category model module.
* @module model/Category
* @version Unknown
*/
export default class Category {
    /**
    * Constructs a new <code>Category</code>.
    * @alias module:model/Category
    * @class
    * @param url {String} 
    * @param id {String} 
    * @param name {String} 
    * @param categoryGroup {String} 
    */

    constructor(url, id, name, categoryGroup) {
        
        
        this['url'] = url;
        this['id'] = id;
        this['name'] = name;
        this['category_group'] = categoryGroup;
        
    }

    /**
    * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Category} obj Optional instance to populate.
    * @return {module:model/Category} The populated <code>Category</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Category();
                        
            
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('hidden')) {
                obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
            }
            if (data.hasOwnProperty('category_group')) {
                obj['category_group'] = ApiClient.convertToType(data['category_group'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} url
    */
    'url' = undefined;
    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Boolean} hidden
    */
    'hidden' = undefined;
    /**
    * @member {String} category_group
    */
    'category_group' = undefined;




}
