/**
 * Control Your Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ClearedEnum.
* @enum {}
* @readonly
*/
export default class ClearedEnum {
        /**
         * value: "uncleared"
         * @const
         */
        uncleared = "uncleared";

        /**
         * value: "cleared"
         * @const
         */
        cleared = "cleared";

        /**
         * value: "reconciled"
         * @const
         */
        reconciled = "reconciled";


    /**
    * Returns a <code>ClearedEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ClearedEnum} The enum <code>ClearedEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
