/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MonthRequest model module.
* @module model/MonthRequest
* @version Unknown
*/
export default class MonthRequest {
    /**
    * Constructs a new <code>MonthRequest</code>.
    * @alias module:model/MonthRequest
    * @class
    * @param month {Date} 
    * @param note {String} 
    */

    constructor(month, note) {
        
        
        this['month'] = month;
        this['note'] = note;
        
    }

    /**
    * Constructs a <code>MonthRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MonthRequest} obj Optional instance to populate.
    * @return {module:model/MonthRequest} The populated <code>MonthRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonthRequest();
                        
            
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Date');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('income')) {
                obj['income'] = ApiClient.convertToType(data['income'], 'Number');
            }
            if (data.hasOwnProperty('budgeted')) {
                obj['budgeted'] = ApiClient.convertToType(data['budgeted'], 'Number');
            }
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], 'Number');
            }
            if (data.hasOwnProperty('to_be_budgeted')) {
                obj['to_be_budgeted'] = ApiClient.convertToType(data['to_be_budgeted'], 'Number');
            }
            if (data.hasOwnProperty('age_of_money')) {
                obj['age_of_money'] = ApiClient.convertToType(data['age_of_money'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Date} month
    */
    'month' = undefined;
    /**
    * @member {String} note
    */
    'note' = undefined;
    /**
    * @member {Number} income
    */
    'income' = undefined;
    /**
    * @member {Number} budgeted
    */
    'budgeted' = undefined;
    /**
    * @member {Number} activity
    */
    'activity' = undefined;
    /**
    * @member {Number} to_be_budgeted
    */
    'to_be_budgeted' = undefined;
    /**
    * @member {Number} age_of_money
    */
    'age_of_money' = undefined;




}
