/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClearedEnum from './ClearedEnum';

/**
* The PatchedTransactionRequest model module.
* @module model/PatchedTransactionRequest
* @version Unknown
*/
export default class PatchedTransactionRequest {
    /**
    * Constructs a new <code>PatchedTransactionRequest</code>.
    * @alias module:model/PatchedTransactionRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PatchedTransactionRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PatchedTransactionRequest} obj Optional instance to populate.
    * @return {module:model/PatchedTransactionRequest} The populated <code>PatchedTransactionRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedTransactionRequest();
                        
            
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('memo')) {
                obj['memo'] = ApiClient.convertToType(data['memo'], 'String');
            }
            if (data.hasOwnProperty('cleared')) {
                obj['cleared'] = ClearedEnum.constructFromObject(data['cleared']);
            }
            if (data.hasOwnProperty('approved')) {
                obj['approved'] = ApiClient.convertToType(data['approved'], 'Boolean');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('payee')) {
                obj['payee'] = ApiClient.convertToType(data['payee'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('payee_name')) {
                obj['payee_name'] = ApiClient.convertToType(data['payee_name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Date} date
    */
    'date' = undefined;
    /**
    * @member {Number} amount
    */
    'amount' = undefined;
    /**
    * @member {String} memo
    */
    'memo' = undefined;
    /**
    * @member {module:model/ClearedEnum} cleared
    */
    'cleared' = undefined;
    /**
    * @member {Boolean} approved
    */
    'approved' = undefined;
    /**
    * @member {String} account
    */
    'account' = undefined;
    /**
    * @member {String} payee
    */
    'payee' = undefined;
    /**
    * @member {String} category
    */
    'category' = undefined;
    /**
    * @member {String} payee_name
    */
    'payee_name' = undefined;




}
