/**
 * Control Your Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PatchedEnvelopeRequest model module.
* @module model/PatchedEnvelopeRequest
* @version Unknown
*/
export default class PatchedEnvelopeRequest {
    /**
    * Constructs a new <code>PatchedEnvelopeRequest</code>.
    * @alias module:model/PatchedEnvelopeRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PatchedEnvelopeRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PatchedEnvelopeRequest} obj Optional instance to populate.
    * @return {module:model/PatchedEnvelopeRequest} The populated <code>PatchedEnvelopeRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedEnvelopeRequest();
                        
            
            if (data.hasOwnProperty('budgeted')) {
                obj['budgeted'] = ApiClient.convertToType(data['budgeted'], 'Number');
            }
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], 'Number');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} budgeted
    */
    'budgeted' = undefined;
    /**
    * @member {Number} activity
    */
    'activity' = undefined;
    /**
    * @member {Number} balance
    */
    'balance' = undefined;




}
