/**
 * Control Your Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import CategoryGroup from '../model/CategoryGroup';
import CategoryGroupRequest from '../model/CategoryGroupRequest';
import PatchedCategoryGroupRequest from '../model/PatchedCategoryGroupRequest';

/**
* Categorygroup service.
* @module api/CategorygroupApi
* @version Unknown
*/
export default class CategorygroupApi {

    /**
    * Constructs a new CategorygroupApi. 
    * @alias module:api/CategorygroupApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the categorygroupCreate operation.
     * @callback module:api/CategorygroupApi~categorygroupCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Concrete view for listing a queryset or creating a model instance.
     * @param {module:api/CategorygroupApi~categorygroupCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryGroup}
     */
    categorygroupCreate(body, name, hidden, deleted, name, hidden, deleted, budgetId, callback) {
      let postBody = body;

      let pathParams = {
        'budget_id': budgetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'hidden': hidden,
        'deleted': deleted,
        'name': name,
        'hidden': hidden,
        'deleted': deleted
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = CategoryGroup;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/categorygroup/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the categorygroupList operation.
     * @callback module:api/CategorygroupApi~categorygroupListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CategoryGroup>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Concrete view for listing a queryset or creating a model instance.
     * @param {module:api/CategorygroupApi~categorygroupListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CategoryGroup>}
     */
    categorygroupList(budgetId, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CategoryGroup];

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/categorygroup/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the categorygroupPartialUpdate operation.
     * @callback module:api/CategorygroupApi~categorygroupPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/CategorygroupApi~categorygroupPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryGroup}
     */
    categorygroupPartialUpdate(budgetId, id, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'budget_id': budgetId,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'hidden': opts['hidden'],
        'deleted': opts['deleted'],
        'name': opts['name'],
        'hidden': opts['hidden'],
        'deleted': opts['deleted']
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = CategoryGroup;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/categorygroup/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the categorygroupRetrieve operation.
     * @callback module:api/CategorygroupApi~categorygroupRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/CategorygroupApi~categorygroupRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryGroup}
     */
    categorygroupRetrieve(budgetId, id, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CategoryGroup;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/categorygroup/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the categorygroupUpdate operation.
     * @callback module:api/CategorygroupApi~categorygroupUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/CategorygroupApi~categorygroupUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryGroup}
     */
    categorygroupUpdate(body, name, hidden, deleted, name, hidden, deleted, budgetId, id, callback) {
      let postBody = body;

      let pathParams = {
        'budget_id': budgetId,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'hidden': hidden,
        'deleted': deleted,
        'name': name,
        'hidden': hidden,
        'deleted': deleted
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = CategoryGroup;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/categorygroup/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
