/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Envelope from '../model/Envelope';
import Month from '../model/Month';
import PatchedEnvelopeRequest from '../model/PatchedEnvelopeRequest';

/**
* Months service.
* @module api/MonthsApi
* @version Unknown
*/
export default class MonthsApi {

    /**
    * Constructs a new MonthsApi. 
    * @alias module:api/MonthsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the monthsCategoryPartialUpdate operation.
     * @callback module:api/MonthsApi~monthsCategoryPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Envelope} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/MonthsApi~monthsCategoryPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Envelope}
     */
    monthsCategoryPartialUpdate(budgetId, categoryId, month, year, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'budget_id': budgetId,
        'category_id': categoryId,
        'month': month,
        'year': year
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'budgeted': opts['budgeted'],
        'activity': opts['activity'],
        'balance': opts['balance'],
        'budgeted': opts['budgeted'],
        'activity': opts['activity'],
        'balance': opts['balance']
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Envelope;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/months/{year}-{month}/category/{category_id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the monthsCategoryRetrieve operation.
     * @callback module:api/MonthsApi~monthsCategoryRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Envelope} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/MonthsApi~monthsCategoryRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Envelope}
     */
    monthsCategoryRetrieve(budgetId, categoryId, month, year, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId,
        'category_id': categoryId,
        'month': month,
        'year': year
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Envelope;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/months/{year}-{month}/category/{category_id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the monthsList operation.
     * @callback module:api/MonthsApi~monthsListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Month>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/MonthsApi~monthsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Month>}
     */
    monthsList(budgetId, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Month];

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/months/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the monthsRetrieve operation.
     * @callback module:api/MonthsApi~monthsRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Month} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/MonthsApi~monthsRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Month}
     */
    monthsRetrieve(budgetId, month, year, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId,
        'month': month,
        'year': year
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Month;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/months/{year}-{month}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
