/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import PatchedPayeeRequest from '../model/PatchedPayeeRequest';
import Payee from '../model/Payee';
import PayeeRequest from '../model/PayeeRequest';

/**
* Payee service.
* @module api/PayeeApi
* @version Unknown
*/
export default class PayeeApi {

    /**
    * Constructs a new PayeeApi. 
    * @alias module:api/PayeeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the payeeCreate operation.
     * @callback module:api/PayeeApi~payeeCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payee} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Concrete view for listing a queryset or creating a model instance.
     * @param {module:api/PayeeApi~payeeCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payee}
     */
    payeeCreate(body, name, transferAccountId, deleted, name, transferAccountId, deleted, budgetId, callback) {
      let postBody = body;

      let pathParams = {
        'budget_id': budgetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'transfer_account_id': transferAccountId,
        'deleted': deleted,
        'name': name,
        'transfer_account_id': transferAccountId,
        'deleted': deleted
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Payee;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/payee/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payeeList operation.
     * @callback module:api/PayeeApi~payeeListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Payee>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Concrete view for listing a queryset or creating a model instance.
     * @param {module:api/PayeeApi~payeeListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Payee>}
     */
    payeeList(budgetId, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Payee];

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/payee/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payeePartialUpdate operation.
     * @callback module:api/PayeeApi~payeePartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payee} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/PayeeApi~payeePartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payee}
     */
    payeePartialUpdate(budgetId, id, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'budget_id': budgetId,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'transfer_account_id': opts['transferAccountId'],
        'deleted': opts['deleted'],
        'name': opts['name'],
        'transfer_account_id': opts['transferAccountId'],
        'deleted': opts['deleted']
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Payee;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/payee/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payeeRetrieve operation.
     * @callback module:api/PayeeApi~payeeRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payee} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/PayeeApi~payeeRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payee}
     */
    payeeRetrieve(budgetId, id, callback) {
      let postBody = null;

      let pathParams = {
        'budget_id': budgetId,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Payee;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/payee/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payeeUpdate operation.
     * @callback module:api/PayeeApi~payeeUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payee} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/PayeeApi~payeeUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payee}
     */
    payeeUpdate(body, name, transferAccountId, deleted, name, transferAccountId, deleted, budgetId, id, callback) {
      let postBody = body;

      let pathParams = {
        'budget_id': budgetId,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'transfer_account_id': transferAccountId,
        'deleted': deleted,
        'name': name,
        'transfer_account_id': transferAccountId,
        'deleted': deleted
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Payee;

      return this.apiClient.callApi(
        '/v1/budgets/{budget_id}/payee/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
