/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterMyMoneyApi);
  }
}(this, function(expect, MasterMyMoneyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterMyMoneyApi.AccountApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountApi', function() {
    describe('accountCreate', function() {
      it('should call accountCreate successfully', function(done) {
        //uncomment below and update the code to test accountCreate
        //instance.accountCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountList', function() {
      it('should call accountList successfully', function(done) {
        //uncomment below and update the code to test accountList
        //instance.accountList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountPartialUpdate', function() {
      it('should call accountPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test accountPartialUpdate
        //instance.accountPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountRetrieve', function() {
      it('should call accountRetrieve successfully', function(done) {
        //uncomment below and update the code to test accountRetrieve
        //instance.accountRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountTransactionList', function() {
      it('should call accountTransactionList successfully', function(done) {
        //uncomment below and update the code to test accountTransactionList
        //instance.accountTransactionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
