/**
 * Master My Money API
 * Direct access to your budgets. Or use the APP
 *
 * OpenAPI spec version: Unknown
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterMyMoneyApi);
  }
}(this, function(expect, MasterMyMoneyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterMyMoneyApi.CategorygroupApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CategorygroupApi', function() {
    describe('categorygroupCreate', function() {
      it('should call categorygroupCreate successfully', function(done) {
        //uncomment below and update the code to test categorygroupCreate
        //instance.categorygroupCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('categorygroupList', function() {
      it('should call categorygroupList successfully', function(done) {
        //uncomment below and update the code to test categorygroupList
        //instance.categorygroupList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('categorygroupPartialUpdate', function() {
      it('should call categorygroupPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test categorygroupPartialUpdate
        //instance.categorygroupPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('categorygroupRetrieve', function() {
      it('should call categorygroupRetrieve successfully', function(done) {
        //uncomment below and update the code to test categorygroupRetrieve
        //instance.categorygroupRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('categorygroupUpdate', function() {
      it('should call categorygroupUpdate successfully', function(done) {
        //uncomment below and update the code to test categorygroupUpdate
        //instance.categorygroupUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
